run_name: ???
experiment: ???
train: True
evaluate: True
plot: True

use_gpu: True
device: 0
use_tf32: False
use_amp: False
num_cpus: 0
dry_run: False
submit: False
run_dir: runs

prev_exp_dir: null
w_prev_path: null
num_bnn_samples: null

data:
  num: -1
  path_exp: ${dataset.dir}/data_train
  path_sim: ${dataset.dir}/sim_train
  path_exp_test: ${dataset.dir}/data_test
  path_sim_test: ${dataset.dir}/sim_test   
  val_frac: 0.1
  on_gpu: True

training:
  epochs: 1
  lr: 1.e-3
  batch_size: 32
  test_batch_size: 4096
  optimizer:
    _target_: torch.optim.AdamW
    weight_decay: 0.
  scheduler: {}
  gradient_norm: null
  validate_freq: 1
  patience: null
  save_best_epoch: True
  save_freq: null
  warm_start: null
  warm_start_epoch: null
  use_tensorboard: True
  log_iters: 500

plotting:
  pagewidth: 9.6
  num_bins: 45
  hadron_obs_labels:
    - $T$
    - $C$
    - $D$
    - $B_{W}$
    - $B_{T}$
    - $n_{f}$
    - $n_{\mathrm{ch}}$
    - $\langle |\ln x_f|\rangle$
    - $\langle (|\ln x_f|-\langle |\ln x_f|\rangle)^2\rangle$
    - $\langle (|\ln x_f|-\langle |\ln x_f|\rangle)^3\rangle$
    - $\langle |\ln x_{\rm ch}|\rangle$
    - $\langle (|\ln x_{\rm ch}|-\langle |\ln x_{\rm ch}|\rangle)^2\rangle$
    - $\langle (|\ln x_{\rm ch}|-\langle |\ln x_{\rm ch}|\rangle)^3\rangle$

defaults:
  - cluster: slurm
  - dataset: qq 
  - hydra
  - _self_
